# create role admin with createdb login password 'password';

development:
  database: myapp_development
  username: admin
  password: password
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5

test:
  database: myapp_test
  username: admin
  password: password
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
